name: formatting-check
on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  check_formatting:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versions: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install nx
        run: npm add -g nx

      - name: Setup pnpm global bin
        run: pnpm setup

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Node cache
        id: pnpm-cache
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm install

      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: csv

      - name: Lint all projects
        run: nx run-many --target=lint --all

      - name: Check formatting with Prettier
        run: pnpm exec prettier --check .
