name: formatting-check
on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  check_formatting:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versions: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Node cache
        id: pnpm-cache
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm install

      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: csv

      - name: Run scoped actions
        uses: DukeManh/scoped-actions@v1
        with:
          files: ${{ steps.files.outputs.added_modified}}
          eslintTarget: "**/*.{jsx,tsx,ts,js}"
          s0: "pnpm run eslint"
          s1: "pnpm run prettier --check"
