name: Publish node.js Package
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: npx nx run-many -t build --all
      - run: npx nx run-many -t test:noninteractive --all --skip-nx-cache || npx nx run-many -t test --all --skip-nx-cache || true
      - run: npx nx run-many -t publish --all --skip-nx-cache
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
